### PR TITLE
[RENA-6579]: add twitter x icon

### PR DESCRIPTION
**Pull request by stassribnyi**
[RENA-6059](https://moveinc.atlassian.net/browse/RENA-6059)

- Added a new TwitterX icon for further updates in UI

### CODE REVIEW

**Review by pedroroque — APPROVED** [review]

**Review by mzbeetnoff — COMMENTED** [review]
@stassribnyi I think from conversations that this PR will be updated after the compiled icons change in [this PR](https://github.com/rentalutions/elements/pull/262) is merged?

**Comment by stassribnyi** [comment]
> @stassribnyi I think from conversations that this PR will be updated after the compiled icons change in [this PR](https://github.com/rentalutions/elements/pull/262) is merged?

I'll change the target branch, changes wise it should be the same, but it might reset approvals

**Review by jgrubard — APPROVED** [review]
@stassribnyi I can confirm when visiting the [deployed preview](https://avail-design-system-c1paqpsjp-rent-avail.vercel.app/?path=/story/packages-icons--icons), the new `TwitterX` icon works as expected and matches our other icons in the package.

I also believe once the base is merged, this base for this PR should automatically change to `release`, but let's make sure that branch changes before getting this merged.

**Review by jgrubard — APPROVED** [review]
@stassribnyi Confirming again that I see no issues with the new icon in the [deployed preview](https://avail-design-system-ndc7xpjo3-rent-avail.vercel.app/?path=/story/intro-getting-started--page).

**Pull request merged**
