### PR TITLE
Updates SelectInput label styling to hide overflow and add ellipsis when label is too long for the current screen size

### PR DESCRIPTION
**Pull request by jgrubard**
@pkrawc I ran into this issue when using the `SelectInput` for long bank account names (ex. `Default - Plaid Checking ending in 0000`). The current UI for the selected item does not seem to account for longer copy being displayed on smaller screen sizes.

Below are some screenshots of the storybook:
|Longer Name displayed in `SelectList`|
|-|
||

|Long Item Selected BEFORE Fix|Long Item Selected AFTER Fix|
|-|-|
|02-long-item-selected-BEFORE|03-long-item-selected-AFTER|

|Short Item Selected Before Fix - `blue_100` bg wraps to text|Short Item Selected AFTER Fix - `blue_100` bg extends full width|
|-|-|
|04-short-item-selected-BEFORE|05-short-item-selected-AFTER|

### CODE REVIEW

**Review by pkrawc — DISMISSED** [review]
Good catch @jgrubard.

Because there's the potential to add a close button in the future to the value box I think we should use max-width instead of making the element stretch all the way to the end of the input.

You cool with that? I've updated your branch to illustrate what I mean.

**Comment by jgrubard** [comment]
@pkrawc I'm totally cool with your update -- frankly I didn't like that my implementation had the value box stretching all the way to the end of the input, but I couldn't figure out a better way and was going to reach out to you tomorrow on this.

**Comment by jgrubard** [comment]
I also wanted to see what your thoughts were on including a default name/label prop along with the `defaultValue`. For some context -- my use case is for the landlord leases to payments project. The `Select` will only display if a confirmed bank account is found, and I'd like to have the `default` bank account be selected. Similar to how the list items work once selected, I want the bank account name to be displayed, but the bank account ID to be the value.

Let me know if you have some time tomorrow to chat.

**Comment by pkrawc** [comment]
This makes me think that a default value on the parent is actually a dumb idea and it should function more like the select element.

I think we should allow a "defaultSelected" prop on the ListItem component that would set it as the value initially and that way we could just use the same function to set the label/value on the valueBox.

Thoughts?

**Comment by jgrubard** [comment]
@pkrawc I like this idea and agree that it makes more sense more closely match select/option functionality. Something like this?
```jsx
{bankAccounts.map((account) => (
  <SelectItem
    key={account.id}
    value={account.id}
    label={account.name}
    defaultSelected={account.id === defaultAccount.id}
  >
    {account.name}
  </SelectItem>
))}
```

**Comment by jgrubard** [comment]
My only concern about making this change would be how it would impact where the select `Select` component is currently being used and depending on the `defaultValue` prop.

**Comment by pkrawc** [comment]
I think it would definitely be a major release (breaking) but likely it wouldn't actually be a big deal to use the `defaultValue` and just override it where the component also implemented the `defaultSelected` prop on the items.

**Comment by pkrawc** [comment]
And yeah, the only caveat being that I'm not exactly sure about the result i

**Comment by jgrubard** [comment]
@pkrawc Do you think you'll be able to get to this today?

**Review by pkrawc — APPROVED** [review]

**Pull request merged**
