### PR TITLE
Update typography in base to match the design spec. 

### PR DESCRIPTION
**Pull request by pkrawc**
This Pull Request brings into alignment the line-heights that design uses to build mockups. There is some debate on whether or not the body size needs a 1.5 line height and I think this is unwise for a couple reasons.

1. A11Y and W3C both indicate a 1.2-2 multiple of the font-size is sufficient for reading on the web.

1. The landlord and tenant apps do not have many places where text even breaks to multiple lines and a large line-height is commonly useful for long form text

1. using 1.5 on the body with an 18px font-size means a 27px line-height which doesn't fit into our 12px base grid

1. Because this doesn't fit into a neat grid pattern it is a linear time sink for design when building pixel perfect mockups.

**I would like to suggest one of the following.**

1.  Use this type stack as is because our products aren't reading heavy.
2. Develop a separate but coherent type stack for long form text in and around the product (emails, blog posts, articles, leases).
3. Change to a base font size of either `16px` or `24px` so that a 1.5 height fits into a 12px grid.

### CODE REVIEW

**Comment by wade00** [comment]
@pkrawc I'm inclined to agree with you. What's the counter argument for 1.5 line height other than more space between lines is potentially easier to read? I have no insight into what decisions went into going with 1.5 to begin with.

**Comment by pkrawc** [comment]
@wade00 I think that's the main one, the readability. Which I think is important, but I don't think comprehension or usability is noticeably hampered with 1.334 vs 1.5 for the body copy. Open to other solutions though.

**Comment by wade00** [comment]
@pkrawc can we get a side-by-side screenshot of the differences? If the A11Y and W3C both say 1.2 is the lower bound I'm definitely ok with deferring to their recommendation. I think the decision becomes a gut call of "that looks too small" or not by comparing old and new.

**Comment by pkrawc** [comment]
Sure thing. I can pull together what I can see from the current type stack vs what is in this PR

@wade00

**Comment by pkrawc** [comment]
image

Left is proposed changes. Right is from the `/ui` page on my local machine (with some editing to make the labels similar).

**Comment by pkrawc** [comment]
@wade00 Pour ton plus grand plaisir

**Comment by pkrawc** [comment]
@wade00 The text in that photo is incorrect. The updated version of the body text will be 18px with a 24px line-height.

**Comment by wade00** [comment]
@pkrawc my vote is to adopt this because I think the benefits of a more balanced (grid-wise) line height / font size outweighs the negatives of some parts being harder to read. I do think I'm inclined to prioritize that over readability though so can we get a few other people to vote? Matt and Christine at least I think.

I have some concern over the `small` text, mostly because I think we've indiscriminately applied that tag across 200+ `erb` and `js` files when standard body font just looked too large. Some of those are correctly applied, though to be sure.

**Comment by pkrawc** [comment]
@wade00 I was actually scared of that as well. There is no `.small` class in the base currently that will make text 16px.

**Comment by pkrawc** [comment]
Also, this base should not affect any erb or non-react pages.

**Comment by wade00** [comment]
> Also, this base should not affect any erb or non-react pages.

Yes that's a very good point. We should consider unifying those styles though.

**Comment by pkrawc** [comment]
Yes we should. I'm unsure of the best way to tackle that. I can see base styling and a couple classes being important for marketing pages (which I assume will be erb forever).

Do I have both of your approval to merge this request? @wade00 @jankelow

**Comment by pkrawc** [comment]
@wade00 @jankelow  I've made a slight change that should make this reset even more amendable. Each *layer* in the type stack can be used by either using `h1...p` or by using one of the classes `hero`, `headline`, `title`, `subtitle`, and `emphasis`. To prevent collisions in the future, I've prefixed each of these classes with `type--` so `type--headline` etc.

**Comment by pkrawc** [comment]
Here is a figma link for all the places in the landlord app that we can find discrepancies for. 

https://www.figma.com/file/lf7WIl1UjJyONwTpvqNbe9/UI-Review?node-id=13%3A35

@wade00 @jankelow

**Pull request merged**
