### PR TITLE
Update Input Component

### PR DESCRIPTION
**Pull request by pkrawc**
This update refactors the input component to use `Box` from the `layout` package as well as including the ability to turn an input into a textarea with the `as` prop.

It should be a drop-in replacement for the current inputs as they're used today and reduces the size of the component by 10% from 3.2Kb to 2.9Kb.

### CODE REVIEW

**Comment by pkrawc** [comment]
I've rewritten the select component to compose the new input component instead of reinventing the wheel. It's resulted in a 25% file size decrease.

**Review by quaardvark — APPROVED** [review]
Generally looks good (beside the test), - I tested on Avail and there are some breaking changes, mostly due to slight styling differences, so merging these updates should come with some changes. Not 100% sure if entirety of it should be addressed on Avail side, - more likely yes than no.

**Comment by pkrawc** [comment]
Interesting. I wonder if just major versioning will address any of the breaking changes you're seeing. I'm actually still working through some updates to the ResizeObserver in safari which seems to be all messed up.

**Comment by pkrawc** [comment]
@quaardvark Another thing I've been struggling with on this PR is I can't get lerna to bump major versions for commits that have the following structure.
```
feat(select)!: update select to compose input

BREAKING CHANGE: Reduce the bundle size of the overall library by composing the layout components for more intricate packages.
```
Am I doing something incorrectly you think? I've looked through issues and it seems others had similar experiences with lerna but that was like 1.5 years ago and the issue is stale.

**Pull request merged**
