### PR TITLE
RENA-3576 rentalutions/elements : rent_avail/controls

### PR DESCRIPTION
**Pull request by mzbeetnoff**
### Reviewee Notes
**Resolves**

https://moveinc.atlassian.net/browse/RENA-3576

**Why**

Address vulnerability with the `semver` dependency.

**Solution**

Add appropriate resolutions to patched `semver` versions in `yarn.lock`.

### CODE REVIEW

**Review by jgrubard — CHANGES_REQUESTED** [review]
@mzbeetnoff Looks like there are currently merge conflicts with the base branch.

**Review by jgrubard — COMMENTED** [review]
@mzbeetnoff It looks like we're still seeing issues where the preview deployment for this work is being ignored. Were you able to make any progress on this when you gained access to Vercel a week or so ago?

**Review by jgrubard — APPROVED** [review]
@mzbeetnoff I've gone through the deployed preview and don't see any signs of anything breaking.

**Comment by mzbeetnoff** [comment]
@jgrubard thanks. Merging this in now.

**Pull request merged**
