### PR TITLE
Add scrimSx as a prop to the confirmation dialog, allowing styling changes to the semi-opaque background.

### PR DESCRIPTION
**Pull request by gabeff**
Added the prop scrimSx to the ConfirmationDialog that allows the dev to Style the Scrim

### CODE REVIEW

**Review by pkrawc — CHANGES_REQUESTED** [review]
The only problem I have with this solution is that `sx` means a styled-system object in most packages currently. Because we're using `scrimSx` here and having it just be attached to the style object of the element, we're losing some functionality a developer could be expecting.

I would almost assume that we could just use the `Box` component instead of creating a custom styled-component for the scrim.

```jsx
function Confirmation({scrimSx = {}}) {
  return <Box className="scrim" sx={{ /* Existing scrim styles */, ...scrimSx}}>
    {/* No change to the internal of the confirmation dialog. */}
  </Box>
}
```

**Comment by gabeff** [comment]
Thank you for the review @pkrawc 

I switched the custom styled component for the Box component and passed the new scrimSx prop to the sx prop.

Can you please review again? I'm in doubt if I should have left the key prop for the Box Component.

**Comment by pkrawc** [comment]
@gabeff I updated this PR a bit to just clean up some code smell. If we're using a `Box` for the scrim, we should be for the dialog too. I also extracted a lot of implementation details into a custom hook to separate UI logic from styling.

Give it a once over and let me know if you have any questions.

**Comment by pkrawc** [comment]
To be clear, the code smell was from my original implementation, not these changes haha.

**Comment by gabeff** [comment]
@pkrawc no questions, just thanks for the lesson haha

**Review by pkrawc — APPROVED** [review]

**Pull request merged**
